version: '3.4'

services:
  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile
    depends_on: 
        - shopping.eventstore
        - shopping.readstore

  shopping.eventstore:
    container_name: esdb-docs
    image: eventstore/eventstore:release-5.0.10
    ports:
      - '2113:2113'
      - '1113:1113'
    environment:
      EVENTSTORE_EXT_HTTP_PORT: 2113
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_RUN_PROJECTIONS: all
      EVENTSTORE_START_STANDARD_PROJECTIONS: 'true'
      PROJECTION_THREADS: 8
      EVENTSTORE_INT_TCP_HEARTBEAT_TIMEOUT: '50000'
   


  shopping.readstore:
    container_name: "mssqlDB"
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    ports:
       - "1433:1433" 


